import React, { useState } from 'react';
import Image from 'next/image';
import axios from 'axios';
import Stripe from 'stripe';
import { loadStripe } from '@stripe/stripe-js';
import toast from 'react-hot-toast';
import { TextField, Menu, MenuItem, Button } from '@mui/material';
import { inputFields, branchNames, degreeNames } from 'constants/register';
import PageHead from 'components/PageHead';
import { sanitizeData } from 'utils/util';
import { setLs, lsKeys } from 'utils/lsUtil';

const textFieldSx = { width: 400 };

const dropdowns = [
  { id: 'degree', label: 'Degree', list: degreeNames, open: 'openDegree' },
  { id: 'branch', label: 'Branch', list: branchNames, open: 'openBranch' },
];

function generate4DigitNumber() {
  return Math.floor(Math.random() * 10000) + 1;
}

const stripePromise = loadStripe(process.env.NEXT_PUBLIC_STRIPE_PUBLIC_KEY);

export default function Register({ prices }) {
  const [payloadData, setPayloadData] = useState({
    fullName: '',
    email: '',
    registerNumber: '',
    phone: '',
    year: '',
    degree: '',
    branch: '',
    referralCode: '',
  });
  const [error, setError] = useState({
    fullName: false,
    email: false,
    registerNumber: false,
    phone: false,
    year: false,
    degree: false,
    branch: false,
    referralCode: false,
  });
  const [anchorElDegree, setAnchorElDegree] = useState(null);
  const [anchorElBranch, setAnchorElBranch] = useState(null);
  const openVar = {
    openDegree: Boolean(anchorElDegree),
    openBranch: Boolean(anchorElBranch),
  };
  const handleClick = (event, id) => {
    if (id === 'degree') setAnchorElDegree(event.currentTarget);
    else setAnchorElBranch(event.currentTarget);
  };

  const handleClose = (e, id) => {
    const value = e.target.getAttribute('name');
    if (value) setPayloadData({ ...payloadData, [id]: value });
    if (id === 'degree') setAnchorElDegree(null);
    else setAnchorElBranch(null);
  };

  const onChange = (event, key) => {
    const { value } = event.target;
    setPayloadData({ ...payloadData, [key]: value });
  };

  const onSubmit = async (event, paymentMode) => {
    event.preventDefault();
    const { data, errors } = sanitizeData(payloadData);
    setError(errors);
    if (Object.values(errors).includes(true)) {
      toast.error('Fill all fields to continue');
      return;
    } else {
      setPayloadData(data);
      const username =
        data.fullName.substring(0, 15).toLowerCase().replace(/\s/g, '_') +
        generate4DigitNumber();
      setLs(lsKeys.firebaseRegUserRef, username);
      await axios({
        baseURL: window.location.origin,
        method: 'POST',
        url: '/api/registration',
        data: { ...data, username, hasPaidOnline: false },
      });
    }
    if (paymentMode === 'online-payment') {
      // Launch stripe checkout session
      const res = await axios({
        baseURL: window.location.origin,
        method: 'POST',
        url: '/api/checkout_session',
        data: {
          priceId: prices[0].id,
          email: data.email || '',
        },
      });
      window.location = res.data.url;
    }
  };

  return (
    <>
      <PageHead
        title="SYCon2022 - Creating Leaders and Inspiring Change"
        description="Generated by create next app"
      />

      <div className="register-container">
        <div className="cover-container">
          <Image src="/logo.svg" alt="SYCon" width={127} height={53} />
          <h1>SYCon</h1>
          <p>Creating leaders and inspiring change</p>
        </div>
        <div className="register-form">
          <h3>Student Registration</h3>
          <div className="input-fields">
            {inputFields.map(field => (
              <div className="input-container" key={field.id}>
                <TextField
                  sx={textFieldSx}
                  value={payloadData[field.id]}
                  type={field.type}
                  label={field.label}
                  onChange={e => onChange(e, field.id)}
                  inputProps={field.props}
                  error={error[field.id]}
                  required
                />
              </div>
            ))}

            <div className="dropdown-input">
              {dropdowns.map(dd => (
                <div className="input-container" key={dd.id}>
                  <TextField
                    value={payloadData[dd.id]}
                    label={dd.label}
                    id={`${dd.id}-button`}
                    onClick={e => handleClick(e, dd.id)}
                    aria-controls={
                      openVar[dd.open] ? `${dd.id}-menu` : undefined
                    }
                    aria-haspopup="true"
                    aria-expanded={openVar[dd.open] ? 'true' : undefined}
                    disabled={!error[dd.id]}
                    error={error[dd.id]}
                    required
                  />
                  <Menu
                    id={`${dd.id}-menu`}
                    anchorEl={
                      dd.id === 'degree' ? anchorElDegree : anchorElBranch
                    }
                    open={openVar[dd.open]}
                    onClose={e => handleClose(e, dd.id)}
                    MenuListProps={{ 'aria-labelledby': 'degree-button' }}
                  >
                    {dd.list.map(item => (
                      <MenuItem
                        onClick={e => handleClose(e, dd.id)}
                        name={item}
                        key={item}
                      >
                        {item}
                      </MenuItem>
                    ))}
                  </Menu>
                </div>
              ))}
            </div>
            <div className="input-container">
              <TextField
                sx={textFieldSx}
                value={payloadData.referralCode}
                label="Referral Code"
                onChange={e => onChange(e, 'referralCode')}
                inputProps={{
                  inputMode: 'numeric',
                  pattern: '[0-9]*',
                  maxLength: 4,
                }}
                error={error.referralCode}
                required
              />
            </div>
          </div>
          <div className="payment-container">
            <Button
              variant="contained"
              size="large"
              sx={{ width: 180 }}
              color="info"
              onClick={e => onSubmit(e, 'online-payment')}
            >
              Pay Now
            </Button>
            <Button
              variant="outlined"
              size="large"
              sx={{ width: 180 }}
              color="info"
              onClick={e => onSubmit(e, 'offline-payment')}
            >
              Pay Later
            </Button>
          </div>
        </div>
      </div>
    </>
  );
}

export const getServerSideProps = async () => {
  const stripe = new Stripe(process.env.STRIPE_SECRET_KEY, {
    apiVersion: '2020-08-27',
  });
  const prices = await stripe.prices.list({
    active: true,
  });
  return { props: { prices: prices.data } };
};
